### ISSUE TITLE
(23.03.31) 수정사안

### ISSUE THREAD

**Issue by jini5** [fastcampus-final/go-together-be#100]
## Title
배포한 브랜치 확인 후 생긴 이슈입니다.

## Tasks

- [x] 회원정보요청시 패스워드 빼고 전부 반환되도록해야합니다. #31 
- [x] 장바구니  content갯수 0개 일때 예외처리 #27 
- [x] 카테고리 상품 검색에서 content갯수 0개 일때 예외처리 #38 
- [x] FE요구사항- 관리자 계정 회원 리스트 조회 시 관리자 여부 추가 #31 
- [x] UserDTO 코드 리팩토링 필요
