### ISSUE TITLE
Refactor: 23.04.03 이슈 정리

### ISSUE THREAD

**Issue by jini5** [fastcampus-final/go-together-be#109]
## Title
FE에서 베포된 사항 확인 후 요청한 사항들 정리 목록입니다. 

## Tasks

- [x] 페이지 쿼리스트링을 page 로 통합
- [x] 상세정보 api url 통합
- [x] admin의 사용자 정보 수정 요청 사항
![image](https://user-images.githubusercontent.com/103543611/229762271-a990420b-35e9-4caa-a87b-ef368ea2a020.png)
- [x] 상품 옵션의 날짜값 String으로 전달
![image](https://user-images.githubusercontent.com/103543611/229767797-614e3ae8-4e4b-4c7c-8fa2-634c7c55ff7e.png)

## References
