### ISSUE TITLE
Refact : 배너 출력 방식 변경

### ISSUE THREAD

**Issue by cutegyuseok** [fastcampus-final/go-together-be#156]
## Title
배너 출력방식을 image only에서 image + 테그 + 제목 + 소제목 으로 변경

## Tasks

- [ ] Banner table 변경
- [ ] Banner 추가 dto 및 입력 기능 수정
- [ ] Banner 수정 기능 수정
- [ ] Banner 출력 기능 수정
