### ISSUE TITLE
FE API 변경 사항 알림

### ISSUE THREAD

**Issue by cutegyuseok** [fastcampus-final/go-together-be#23]
## Title

FrontEnd API 변경 사항

## Tasks

- [x] 카테고리 상품 조회에서 /products/categories?categoryId=2를 PathVariable를 이용해서 /products/categories/2 변경
- [x] 게시글 생성,조회,수정,삭제 추가
- [x] 한줄 후기 기능 삭제
- [x] #108
- [x] 예약 상태 목록 
      1. PENDING("주문 접수")
      2. CONFIRMED("예약 완료")
      3. PAYMENT_PENDING("결제 대기중")
      4. PAYMENT_COMPLETE("결제 완료")
      5. CANCEL_REQUESTED("예약 취소 요청")
      6. CANCELLED("예약 취소")
      7. COMPLETED("여행 완료")
      8. UNDECIDED("미정")
- [x] 상품 상태 목록 
      1. FOR_SALE("판매중")
      2. STOPSELLING("판매중지")
      3. HIDING("숨김")
- [x] 예약인원 number -> numberOfPeople로 변경
- [x] 현 API 응답 예시와 달리 응답할 데이터가 있는 경우만 responsebody에 데이터가 담겨서 날아갈 계획( status, code, message 삭제)
- [x] 장바구니에서 상품 총 결제가격은 보내지 않고 상품의 가격, 갯수와 싱글룸의 가격,갯수만 보내게 되었습니다.
- [x] Request 중 pk( ~~Id)를 서버에 보내는 경우 PathVariable 사용
