### ISSUE TITLE
ERD 변경사항 목록

### ISSUE THREAD

**Issue by ykim-yeji** [fastcampus-final/go-together-be#24]
## Title
ERD 변경사항 목록

## Tasks

- [x] banner 테이블과 product 테이블 N:1 연결 (추가사항)
- [x] '테이블명_id' 로 컨벤션 통일
- [x] 컬럼이름앞에 테이블명 제외
- [x] 게시판 기능,댓글 기능에 작성일,수정일 추가
- [x] 모든 필드를 varchar(255)로 통일하지 말고 각 필드에 맞게 변경하기

**Comment by jini5** [comment]
![go-together-be (1)](https://user-images.githubusercontent.com/113501152/226932558-60db258e-2a59-4b82-8560-88ab56569448.png)
