### ISSUE TITLE
Spring boot Init & JWT customize

### ISSUE THREAD

**Issue by cutegyuseok** [fastcampus-final/go-together-be#3]
## Title
Spring Boot init 후 security 와 jwt 관련 간단한 개발.

## Description

Spring Boot initialize
Swagger config
Spring Security customize
JWT customize
Role (ADMIN, USER)
Test API
## Tasks

- [x] Spring Boot initialize
- [x] JWT & Spring Security customize
- [x] Create basic Api

## References

- [참고 깃허브(본인 기존 프로젝트)](https://github.com/FastcampusMini/mini-project)

**Comment by cutegyuseok** [comment]
관련 설정파일은 디스코드에 올려두었습니다.

**Comment by cutegyuseok** [comment]
http://localhost:8080/swagger-ui/index.html Swagger 주소
