### ISSUE TITLE
Feat: 사용자 관련 API

### ISSUE THREAD

**Issue by cutegyuseok** [fastcampus-final/go-together-be#31]
## Title
사용자 관련 API backlog

## Tasks

- [ ] 회원 정보 수정
- [x] 회원 상세 정보 조회
- [x] 회원 탈퇴
- [ ] 여행 유형 추가
