### ISSUE TITLE
Feat: 상품 검색 조회

### ISSUE THREAD

**Issue by cutegyuseok** [fastcampus-final/go-together-be#33]
## Title

상품 키워드를 통한 검색 조회

## Tasks

- [x] 검색 조회 API
- [x] 최신순, 가격 내림차순, 오름차순 정렬
- [x] 기준 날짜 조건 
- [x] 함께하는 인원수 조건

**Comment by cutegyuseok** [comment]
#73
