### ISSUE TITLE
Feat: 페이지 관련 API

### ISSUE THREAD

**Issue by cutegyuseok** [fastcampus-final/go-together-be#34]
## Title

페이지 출력 관련 API

## Tasks

- [x] 카테고리 목록 조회
- [x] 추천 상품 조회 (회원)
- [ ] 추천 상품 조회 (비회원)
- [x] 배너
- [x] 인기 여행지
