### ISSUE TITLE
인기 여행지 관리 기능

### ISSUE THREAD

**Issue by cutegyuseok** [fastcampus-final/go-together-be#66]
## Title

메인 페이지 인기 도시 노출과 , 검색 페이지 인기 도시 노출을 위한 관리 시스템

## Description

예상 필요 컬럼
PK
도시 이름
도시 이미지
노출 중요도
## Tasks

- [x] 인기도시 Entity 설계
- [x] 인기도시 DB table 추가
- [x] 인기도시 추가 기능
- [x] 인기도시 리스트 보기 기능
- [x] 인기도시 수정 기능
- [x] 인기도시 삭제 기능
