### ISSUE TITLE
3월 27일 회의결과 추가 내용

### ISSUE THREAD

**Issue by cutegyuseok** [fastcampus-final/go-together-be#70]
## Title
3월 27일 회의 결과 추가 내용
## Tasks

- [x] 메인 페이지 회원 그룹별 상품 추천
- [x] 베스트 여행( 예약 인기 순)
- [x] 인기 여행지( 관리자가 만든 기준)
- [x] 커뮤니티 통합( 여행 후기, 알려드립니다, 자료실)
- [x] 여행 성향 테스트 결과 -> 그룹화 in 백엔드
- [x] 상품 검색 정렬 세분화( 최신순, 낮은 가격순, 높은 가격순)
